[custom_commands."show oplog diff patch"]
key = ["s"]
args = ["op", "show",  "$operation_id", "--patch", "--color", "always"]
show = "diff"

[preview]
revision_command = ["show", "--color", "always", "-r", "$change_id", "--config", "ui.diff-formatter=delta-non-split"]
