[terminal]
shell = "wsl"

[general]
import = [
  "themes\\catppuccin_mocha.toml",
]

[window]
decorations = "None"
padding = { x = 4, y = 4 }

[font]
normal = { family = "Firge Nerd Console" }
size = 12

[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "Quit" },
  # pass through
  { key = "Space", mods = "Control", chars = "\u0000" },
  { key = "/", mods = "Control", chars = "\u001f" },
]
